### ISSUE TITLE
Find a name for State

### ISSUE THREAD

**Issue by francesco-romano** [robotology-playground/WB-Toolbox#5]
Currently the State component / block returns not only the state, but also other stuff (torques, etc).

You should find a proper name for state (and by the way also in the WholeBodyInterface)

cc @traversaro  @DanielePucci @iron76

**Comment by DanielePucci** [comment]
I know you do not like sensors, guys

**Comment by francesco-romano** [comment]
I do not like sensors, but maybe the others are ok with it.
Currently I called the block "Estimate"

**Comment by DanielePucci** [comment]
`Estimate` :+1:

**Comment by DanielePucci** [comment]
@traversaro ?

**Comment by traversaro** [comment]
If I recall well, estimate was actually the initial name for the state interface. I don't remember why we then switched in some naming (the class name for example) to State. Estimates is definitely a better choice.

**Comment by francesco-romano** [comment]
Great! Estimate decided then!
