### ISSUE TITLE
First  toolbox test

### ISSUE THREAD

**Issue by francesco-romano** [robotology-playground/WB-Toolbox#7]
Before considering complete the first implementation we should test the toolbox.

I think the best way is to port the `torqueBalancing` controller from the old toolbox to this one.
@DanielePucci can you take a look at this on Wednesday?

**Comment by DanielePucci** [comment]
Yes

**Comment by DanielePucci** [comment]
Anyways, I'll start by migrating the `whole-body impedance`, then `torqueBalancing`

**Comment by DanielePucci** [comment]
`torqueBalancing` migrated and tested. 
![out](https://cloud.githubusercontent.com/assets/5045846/11723850/be85e08e-9f70-11e5-885f-eadeaafc99e5.gif)

**Comment by traversaro** [comment]
@DanielePucci  a short list of changes that are necessary to migrate the new WB version (transform all "model" blocks without inputs to take the input from the estimate block, ?? ) will be helpful for other people that needs to migrate.

**Comment by francesco-romano** [comment]
@DanielePucci if you think it is worth the effort you can write a wiki page :smile:

**Comment by DanielePucci** [comment]
Opening an issue on WBI-Toolbox controllers?

**Comment by traversaro** [comment]
It would be better to have somebody that can be accessed by the entry-points (README/Doxygen) for WB/WBI-Toolbox documentation.
